[package]
name = "twenty-one-days-of-rust"
version = "0.1.0"
authors = ["Anand Prem <anand.prem@thoughtworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
